In [55]:
import numpy as np
import pandas as pd
from sklearn import model_selection

In [56]:
column_names = ['Class Name', 'Handicapped Infants','Water Project Cost Sharing',
               'Adoption of the budget resolution', 'Physician fee freeze',
                'El salvador aid', 'Religious groups in schools', 'Anti-satellite test ban',
               'Aid to nicaraguan contras', 'MX Missile', 'Immigration', 
                'Synfuels corporation cutback', 'Education spending', 
                'Superfund right to sue', 'Crime', 'Duty free exports', 
                'Export administration act south africa']

In [57]:
dataframe = pd.read_csv('../data/info.data', names = column_names, header=None);
dataframe.head()

,Class Name,Handicapped Infants,Water Project Cost Sharing,Adoption of the budget resolution,Physician fee freeze,El salvador aid,Religious groups in schools,Anti-satellite test ban,Aid to nicaraguan contras,MX Missile,Immigration,Synfuels corporation cutback,Education spending,Superfund right to sue,Crime,Duty free exports,Export administration act south africa
0,republican,n,y,n,y,y,y,n,n,n,y,?,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,?
2,democrat,?,y,y,?,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,?,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,?,y,y,y,y

### Replacing missing values ? with NaN

In [58]:
dataframe = dataframe.replace('?', np.NaN)
dataframe.head()

,Class Name,Handicapped Infants,Water Project Cost Sharing,Adoption of the budget resolution,Physician fee freeze,El salvador aid,Religious groups in schools,Anti-satellite test ban,Aid to nicaraguan contras,MX Missile,Immigration,Synfuels corporation cutback,Education spending,Superfund right to sue,Crime,Duty free exports,Export administration act south africa
0,republican,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN
2,democrat,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y

### Case 1: Dropping NaN values

In [59]:
dropped_nan_dataframe = dataframe.dropna(how = 'any');
dropped_nan_dataframe.head()

,Class Name,Handicapped Infants,Water Project Cost Sharing,Adoption of the budget resolution,Physician fee freeze,El salvador aid,Religious groups in schools,Anti-satellite test ban,Aid to nicaraguan contras,MX Missile,Immigration,Synfuels corporation cutback,Education spending,Superfund right to sue,Crime,Duty free exports,Export administration act south africa
5,democrat,n,y,y,n,y,y,n,n,n,n,n,n,y,y,y,y
8,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
19,democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
23,democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
25,democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y

### Case 2: Treat missing values as a value

In [67]:
for column in dataframe.columns:
    missing_values_dataframe[column] = missing_values_dataframe[column].fillna('m')
        
missing_values_dataframe.head()

,Class Name,Handicapped Infants,Water Project Cost Sharing,Adoption of the budget resolution,Physician fee freeze,El salvador aid,Religious groups in schools,Anti-satellite test ban,Aid to nicaraguan contras,MX Missile,Immigration,Synfuels corporation cutback,Education spending,Superfund right to sue,Crime,Duty free exports,Export administration act south africa
0,republican,n,y,n,y,y,y,n,n,n,y,m,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,m
2,democrat,m,y,y,m,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,m,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,m,y,y,y,y

### Case 3: Impute missing values

In [75]:
for column in dataframe.columns:
    imputed_dataframe[column] = dataframe[column].fillna(dataframe[column].mode()[0])

imputed_dataframe.head()

,Class Name,Handicapped Infants,Water Project Cost Sharing,Adoption of the budget resolution,Physician fee freeze,El salvador aid,Religious groups in schools,Anti-satellite test ban,Aid to nicaraguan contras,MX Missile,Immigration,Synfuels corporation cutback,Education spending,Superfund right to sue,Crime,Duty free exports,Export administration act south africa
0,republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
2,democrat,n,y,y,n,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,y,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,n,y,y,y,y